### ISSUE TITLE
find-let-bound-lambdas bug?

### ISSUE THREAD

**Issue by liumingc** [akeep/scheme-to-c#2]
in c.ss line 2217, i think it shoud be `(guard (not (memq x a*)))` , not `(guard (not (memq x e*)))`, am i right?

**Comment by akeep** [comment]
Nice catch!  I've added a test case for this to the compiler.

Did you have a test case of your own that showed the problem, or did you find it by code reading?

Thanks again,
-andy:)

**Comment by liumingc** [comment]
I read the code, feel confused, and then run a test :)

**Comment by akeep** [comment]
Nice, thanks for reporting it!
